import { FilmStock } from './types';

// ============================================
// COMPREHENSIVE FILM DATABASE 2025-2026
// Based on scientific characteristics & community consensus
// ============================================

export const FILM_DATABASE: Record<string, FilmStock> = {
  // ==========================================
  // KODAK COLOR NEGATIVE FILMS
  // ==========================================
  'portra_160': {
    name: 'Kodak Portra 160',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 160,
    formats: ['35mm', '120'],
    grain: 2,
    saturation: 5,
    contrast: 4,
    latitude: 8,
    sharpness: 8,
    colorBias: 'neutral_warm',
    skinTones: 10,
    idealLight: ['golden', 'flat', 'mixed'],
    idealEnvironment: ['portrait', 'landscape', 'architecture'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 9.2,
    pricePoint: 'professional'
  },
  'portra_400': {
    name: 'Kodak Portra 400',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 3,
    saturation: 5,
    contrast: 5,
    latitude: 10,
    sharpness: 8,
    colorBias: 'neutral_warm',
    skinTones: 10,
    idealLight: ['golden', 'flat', 'harsh', 'mixed'],
    idealEnvironment: ['portrait', 'street', 'landscape', 'interiors'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 9.5,
    pricePoint: 'professional'
  },
  'portra_800': {
    name: 'Kodak Portra 800',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 800,
    formats: ['35mm', '120'],
    grain: 5,
    saturation: 5,
    contrast: 5,
    latitude: 8,
    sharpness: 7,
    colorBias: 'neutral_warm',
    skinTones: 9,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['interiors', 'street', 'portrait'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.8,
    pricePoint: 'professional'
  },
  'ektar_100': {
    name: 'Kodak Ektar 100',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 100,
    formats: ['35mm', '120'],
    grain: 1,
    saturation: 9,
    contrast: 7,
    latitude: 5,
    sharpness: 10,
    colorBias: 'warm',
    skinTones: 5,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture'],
    pushStops: 0,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.5,
    pricePoint: 'professional'
  },
  'gold_200': {
    name: 'Kodak Gold 200',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 200,
    formats: ['35mm', '120'],
    grain: 5,
    saturation: 6,
    contrast: 6,
    latitude: 7,
    sharpness: 6,
    colorBias: 'warm',
    skinTones: 7,
    idealLight: ['golden', 'mixed'],
    idealEnvironment: ['street', 'portrait', 'landscape'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 8.2,
    pricePoint: 'consumer'
  },
  'ultramax_400': {
    name: 'Kodak Ultramax 400',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 400,
    formats: ['35mm'],
    grain: 6,
    saturation: 7,
    contrast: 6,
    latitude: 7,
    sharpness: 6,
    colorBias: 'warm',
    skinTones: 7,
    idealLight: ['flat', 'mixed', 'harsh'],
    idealEnvironment: ['street', 'landscape'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 8.0,
    pricePoint: 'consumer'
  },
  'colorplus_200': {
    name: 'Kodak ColorPlus 200',
    brand: 'Kodak',
    type: 'color_negative',
    iso: 200,
    formats: ['35mm'],
    grain: 6,
    saturation: 5,
    contrast: 5,
    latitude: 7,
    sharpness: 6,
    colorBias: 'neutral_warm',
    skinTones: 7,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['street', 'portrait'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 7.5,
    pricePoint: 'budget'
  },

  // ==========================================
  // KODAK BLACK & WHITE FILMS
  // ==========================================
  'trix_400': {
    name: 'Kodak Tri-X 400',
    brand: 'Kodak',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 6,
    saturation: 0,
    contrast: 7,
    latitude: 8,
    sharpness: 7,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['harsh', 'flat', 'mixed'],
    idealEnvironment: ['street', 'portrait', 'architecture'],
    pushStops: 3,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 9.4,
    pricePoint: 'professional'
  },
  'tmax_100': {
    name: 'Kodak T-Max 100',
    brand: 'Kodak',
    type: 'bw_negative',
    iso: 100,
    formats: ['35mm', '120'],
    grain: 1,
    saturation: 0,
    contrast: 5,
    latitude: 7,
    sharpness: 10,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture', 'portrait'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 10,
    communityScore: 8.7,
    pricePoint: 'professional'
  },
  'tmax_400': {
    name: 'Kodak T-Max 400',
    brand: 'Kodak',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 3,
    saturation: 0,
    contrast: 5,
    latitude: 8,
    sharpness: 9,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['flat', 'harsh', 'mixed'],
    idealEnvironment: ['street', 'portrait', 'architecture'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 10,
    communityScore: 8.5,
    pricePoint: 'professional'
  },
  'tmax_p3200': {
    name: 'Kodak T-Max P3200',
    brand: 'Kodak',
    type: 'bw_negative',
    iso: 1000,
    formats: ['35mm'],
    grain: 8,
    saturation: 0,
    contrast: 7,
    latitude: 6,
    sharpness: 6,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['flat'],
    idealEnvironment: ['interiors', 'street'],
    pushStops: 2,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 8.3,
    pricePoint: 'professional'
  },

  // ==========================================
  // ILFORD BLACK & WHITE FILMS
  // ==========================================
  'hp5_plus': {
    name: 'Ilford HP5 Plus',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 5,
    saturation: 0,
    contrast: 6,
    latitude: 9,
    sharpness: 7,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['flat', 'harsh', 'mixed'],
    idealEnvironment: ['street', 'portrait', 'architecture'],
    pushStops: 3,
    pullStops: 2,
    reciprocityStart: 1,
    communityScore: 9.3,
    pricePoint: 'professional'
  },
  'fp4_plus': {
    name: 'Ilford FP4 Plus',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 125,
    formats: ['35mm', '120'],
    grain: 2,
    saturation: 0,
    contrast: 5,
    latitude: 8,
    sharpness: 9,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh', 'flat'],
    idealEnvironment: ['landscape', 'architecture', 'portrait'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.8,
    pricePoint: 'professional'
  },
  'delta_100': {
    name: 'Ilford Delta 100',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 100,
    formats: ['35mm', '120'],
    grain: 1,
    saturation: 0,
    contrast: 5,
    latitude: 6,
    sharpness: 10,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.5,
    pricePoint: 'professional'
  },
  'delta_400': {
    name: 'Ilford Delta 400',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 3,
    saturation: 0,
    contrast: 5,
    latitude: 6,
    sharpness: 9,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['flat', 'harsh'],
    idealEnvironment: ['portrait', 'architecture', 'street'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.4,
    pricePoint: 'professional'
  },
  'delta_3200': {
    name: 'Ilford Delta 3200',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 1000,
    formats: ['35mm', '120'],
    grain: 8,
    saturation: 0,
    contrast: 7,
    latitude: 7,
    sharpness: 6,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['flat'],
    idealEnvironment: ['interiors', 'street'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.5,
    pricePoint: 'professional'
  },
  'panf_plus': {
    name: 'Ilford Pan F Plus',
    brand: 'Ilford',
    type: 'bw_negative',
    iso: 50,
    formats: ['35mm', '120'],
    grain: 0,
    saturation: 0,
    contrast: 5,
    latitude: 6,
    sharpness: 10,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 8.6,
    pricePoint: 'professional'
  },

  // ==========================================
  // CINESTILL FILMS
  // ==========================================
  'cinestill_800t': {
    name: 'CineStill 800T',
    brand: 'CineStill',
    type: 'color_negative',
    iso: 800,
    formats: ['35mm', '120'],
    grain: 4,
    saturation: 6,
    contrast: 6,
    latitude: 7,
    sharpness: 7,
    colorBias: 'cool',
    skinTones: 7,
    idealLight: ['mixed'],
    idealEnvironment: ['street', 'interiors'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.7,
    pricePoint: 'premium'
  },
  'cinestill_400d': {
    name: 'CineStill 400D',
    brand: 'CineStill',
    type: 'color_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 4,
    saturation: 6,
    contrast: 5,
    latitude: 8,
    sharpness: 8,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'flat', 'mixed'],
    idealEnvironment: ['street', 'portrait', 'landscape'],
    pushStops: 3,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 8.5,
    pricePoint: 'premium'
  },
  'cinestill_50d': {
    name: 'CineStill 50D',
    brand: 'CineStill',
    type: 'color_negative',
    iso: 50,
    formats: ['35mm'],
    grain: 1,
    saturation: 7,
    contrast: 6,
    latitude: 6,
    sharpness: 10,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'portrait', 'architecture'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 8.6,
    pricePoint: 'premium'
  },

  // ==========================================
  // FUJIFILM
  // ==========================================
  'acros_100ii': {
    name: 'Fujifilm Neopan Acros II',
    brand: 'Fujifilm',
    type: 'bw_negative',
    iso: 100,
    formats: ['35mm', '120'],
    grain: 1,
    saturation: 0,
    contrast: 5,
    latitude: 7,
    sharpness: 10,
    colorBias: 'neutral',
    skinTones: 8,
    idealLight: ['golden', 'harsh', 'flat'],
    idealEnvironment: ['landscape', 'architecture', 'portrait'],
    pushStops: 1,
    pullStops: 1,
    reciprocityStart: 120,
    communityScore: 8.9,
    pricePoint: 'professional'
  },

  // ==========================================
  // LOMOGRAPHY
  // ==========================================
  'lomo_cn_400': {
    name: 'Lomography Color Negative 400',
    brand: 'Lomography',
    type: 'color_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 6,
    saturation: 7,
    contrast: 6,
    latitude: 6,
    sharpness: 6,
    colorBias: 'warm',
    skinTones: 6,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['street'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 7.5,
    pricePoint: 'consumer'
  },
  'lomo_cn_800': {
    name: 'Lomography Color Negative 800',
    brand: 'Lomography',
    type: 'color_negative',
    iso: 800,
    formats: ['35mm', '120'],
    grain: 7,
    saturation: 7,
    contrast: 7,
    latitude: 6,
    sharpness: 5,
    colorBias: 'warm',
    skinTones: 6,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['interiors', 'street'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 7.8,
    pricePoint: 'consumer'
  },
  'lomo_berlin_400': {
    name: 'Lomography Berlin Kino 400',
    brand: 'Lomography',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 6,
    saturation: 0,
    contrast: 5,
    latitude: 8,
    sharpness: 6,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['street', 'portrait'],
    pushStops: 3,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 7.8,
    pricePoint: 'consumer'
  },

  // ==========================================
  // FOMA / ARISTA
  // ==========================================
  'fomapan_100': {
    name: 'Fomapan 100',
    brand: 'Foma',
    type: 'bw_negative',
    iso: 100,
    formats: ['35mm', '120'],
    grain: 3,
    saturation: 0,
    contrast: 6,
    latitude: 6,
    sharpness: 7,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 7.5,
    pricePoint: 'budget'
  },
  'fomapan_400': {
    name: 'Fomapan 400',
    brand: 'Foma',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm', '120'],
    grain: 6,
    saturation: 0,
    contrast: 6,
    latitude: 7,
    sharpness: 6,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['street', 'portrait'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 7.3,
    pricePoint: 'budget'
  },

  // ==========================================
  // KENTMERE
  // ==========================================
  'kentmere_100': {
    name: 'Kentmere 100',
    brand: 'Kentmere',
    type: 'bw_negative',
    iso: 100,
    formats: ['35mm'],
    grain: 3,
    saturation: 0,
    contrast: 5,
    latitude: 6,
    sharpness: 7,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['golden', 'harsh'],
    idealEnvironment: ['landscape', 'architecture'],
    pushStops: 1,
    pullStops: 0,
    reciprocityStart: 1,
    communityScore: 7.2,
    pricePoint: 'budget'
  },
  'kentmere_400': {
    name: 'Kentmere 400',
    brand: 'Kentmere',
    type: 'bw_negative',
    iso: 400,
    formats: ['35mm'],
    grain: 5,
    saturation: 0,
    contrast: 6,
    latitude: 7,
    sharpness: 6,
    colorBias: 'neutral',
    skinTones: 7,
    idealLight: ['flat', 'mixed'],
    idealEnvironment: ['street', 'portrait'],
    pushStops: 2,
    pullStops: 1,
    reciprocityStart: 1,
    communityScore: 7.4,
    pricePoint: 'budget'
  }
};

// Helper to get films by type
export function getFilmsByType(type: 'color' | 'bw'): FilmStock[] {
  const targetType = type === 'color' ? 'color_negative' : 'bw_negative';
  return Object.values(FILM_DATABASE).filter(film => film.type === targetType);
}

// Helper to get films by format
export function getFilmsByFormat(format: '35mm' | '120'): FilmStock[] {
  return Object.values(FILM_DATABASE).filter(film => film.formats.includes(format));
}
